spin_manifest_version = 2

[application]
name = "spin-astro-starter"
description = "Astro website starter for Spin"
version = "0.0.1"

[[trigger.http]]
route = "/"
component = "spin-astro"

[component.spin-astro]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.3/spin_static_fs.wasm", digest = "sha256:38bf971900228222f7f6b2ccee5051f399adca58d71692cdfdea98997965fd0d" }
files = [{ source = "dist", destination = "/" }]

[component.spin-astro.build]
command = "npm run build"